config/routes.rb
Rails.application.routes.draw do

  root 'chats#index'

  get :all_chats, to: 'chats#all_chats' # отображение списка чатов в формате json

  resources :chats do
    resources :messages, only: [:create] # создание сообщений в чате
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy

  validates_presence_of :name
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat

  validates_presence_of :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chats = Chat.all
  end

  def show
    @chat = Chat.find(params[:id])
    @message = Message.new
    @messages = @chat.messages
  end

  def create
    @chat = Chat.new(chat_params)

    if @chat.save
      turbo_stream.append @chat, target: "chats"
    else
      render :index
    end
  end

  def all_chats
    @all_chats = Chat.all
    render json: @all_chats
  end

  private

  def chat_params
    params.permit(:name)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chat = Chat.find(params[:chat_id])
    @message = @chat.messages.create(message_params)
    if @message.save
      broadcast_to_chat(@message.chat)
      respond_to do |format|
        format.html { redirect_to @chat }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@chat) }
      end
    else
      raise 'Не удалось создать сообщение'
    end
  end


  private

  def message_params
    params.permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chats/create.js.erb
<% if @chat.persisted? %>
var chatId = <%= @chat.id %>;
var chatName = "<%= @chat.name %>";
var chatLink = "<%= chat_path(@chat) %>";


var chatList = document.getElementById("chat-list");
var newChatLink = document.createElement("a");
newChatLink.href = chatLink;
newChatLink.textContent = chatName;
chatList.appendChild(newChatLink);


document.getElementById("chat_name").value = '';

<% else %>
<% end %>

app/views/chats/index.html.erb
<div class="sidebar">
  <h1>Список чатов</h1>
  <ul id="chat-list">
    <% @chats.each do |chat| %>
      <li class="chat-item">
        <%= link_to chat.name, chat_path(chat), remote: true %>
        <span class="new-messages-indicator" style="display: none;"></span>
      </li>
    <% end %>
  </ul>
  <div class="create-chat">
    <div id="create-chat-button">
      <div class="plus">+</div>
    </div>
    <div class="tooltip">Создать чат</div>
  </div>
</div>

<div id="create-chat-form" class="hidden">
  <div class="close-form" id="close-chat-form">×</div>
  <%= form_tag(chats_path, method: :post, remote: true) do %>
    <div class="field">
      <%= label_tag :name, 'Название чата:' %>
      <%= text_field_tag :name %>
    </div>
    <div class="actions">
      <%= submit_tag 'Создать чат' %>
    </div>
    <%= turbo_stream_from @chats %>
  <% end %>
</div>

app/views/chats/show.html.erb
<div class="chat-overlay" id="chat-overlay">
  <div class="chat-box">
    <div class="chat-header">
      <h2><%= @chat.name %></h2>
      <span class="close-button" id="close-button">×</span>
    </div>
    <div class="chat-messages">
      <% @messages.each do |message| %>
        <div class="message"><%= message.content %></div>
      <% end %>
    </div>
    <%= form_with(model: [@chat, @message], remote: true) do |form| %>
      <div class="field">
        <%= form.text_field :content %>
      </div>
      <div class="actions">
        <%= form.submit 'Отправить' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <%= turbo_stream_from :all %>
  </body>
</html>

app/views/messages/turbo_stream.erb
<%= turbo_stream.append @message, target: "chat_#{message.chat.id}_messages"%>